apiVersion: v1
kind: Secret
metadata:
  name: monolith-secrets
  namespace: monolith
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://<your-azure-db-host>:5432/appdb"
  DB_USERNAME: "appuser"
  DB_PASSWORD: "Pavan@1234"   # injected from Key Vault via pipeline
